### ISSUE TITLE
ch_pa-1-1_reg 中一个小错误

### ISSUE THREAD

**Issue by Ephmeral** [ics-nju-wl/icspa-public-guide#1]
![image](https://user-images.githubusercontent.com/61184544/168585386-20882cc5-b70c-4025-898f-a985b34edb4f.png)
老师，您好，§1-1.1.2 寄存器 这小节这里低8位寄存器最后一个应该是 bl 吧，文档这里是不是写错了

**Comment by ics-nju-wl** [comment]
确实，已经改正了，感谢提醒！

**Comment by Ephmeral** [comment]
> 确实，已经改正了，感谢提醒！

老师，您好，在PA1-3浮点数中，对于 fpu_test_mul() 和 fpu_test_div() 测试函数中，这里printf 最后打印的应该是浮点数的尾数部分吧，这样的话 significand 是不是应该改为 fraction（因为FLOAT结构体定义的时候，23位尾数是fraction）

![image](https://user-images.githubusercontent.com/61184544/172011801-8f69ed22-bcfa-454c-a100-0c97e490e55f.png)

此外，想想老师请教一下，浮点数在进行乘法的时候是否可能在测试中出现尾数的最后一位与标准结果差1的情况，具体我在 fpu_test_mul() 测试中遇见 denormal_1.fval 和 big_1.fval 相乘的时候出现相差 1 的情况，打印结果如下，我不能确定是我的代码问题，还是本身可能会出现这种情况，因为除了这个测试用例，其他的测试用例我都可以通过，故此向老师请教

![Quicker_20220604_234223](https://user-images.githubusercontent.com/61184544/172013205-be7a9fe0-d71e-46fc-9fd6-d9c221d1a2ed.png)

**Comment by ics-nju-wl** [comment]
回复得很迟了，主要平时不是经常用这个github账号。按照以往的测试经验，乘法尚未遇见过最后一位差1的情况。
