### ISSUE TITLE
错别字勘误 2-2.2.1

### ISSUE THREAD

**Issue by String10** [ics-nju-wl/icspa-public-guide#2]
[代码导读和实验理解-引入Kernel](https://github.com/ics-nju-wl/icspa-public-guide/blob/master/ch/ch_pa-2-2_load_elf.md#2-221-%E5%BC%95%E5%85%A5kernel)

“自然地，在这里我们也将这一功能实现在一个简单地操作系统之中。” $\rightarrow$ “自然地，在这里我们也将这一功能实现在一个简单的操作系统之中。”

**Comment by wangliang-cs** [comment]
收到，感谢指正！
