### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by vcheckzen** [ics-nju-wl/icspa-public-guide#3]
1. 以下引用多写了一个函数，应删除

    https://github.com/ics-nju-wl/icspa-public-guide/blob/83570e87bee0ddbaa22ee6e7e361a54b094f0b77/ch/ch_pa-1-2_alu.md?plain=1#L32-L34

2. 以下引用中，“且不是非规格化浮点数（`exp >`” 后缺少 `0`，应补充

    https://github.com/ics-nju-wl/icspa-public-guide/blob/83570e87bee0ddbaa22ee6e7e361a54b094f0b77/ch/ch_pa-1-3_fpu.md?plain=1#L136

3. 以下引用的注释应改为 `配置目的操作数长度`

    https://github.com/ics-nju-wl/icspa-public-guide/blob/83570e87bee0ddbaa22ee6e7e361a54b094f0b77/ch/ch_pa-2-1_instruction.md?plain=1#L308

**Comment by ics-nju-wl** [comment]
感谢，都修复了。
